### ISSUE TITLE
Add my repos for the jai LSP and tree sitter jai parser

### ISSUE THREAD

**Issue by Pyromuffin** [smari/awesome-jai#1]
Here's my repos for the tree sitter parser and language server implementations.

https://github.com/Pyromuffin/jai-lsp
https://github.com/Pyromuffin/tree-sitter-jai

**Comment by smari** [comment]
Hi! Happy to add them, but correct me if I'm wrong -- these appear not to actually be written in Jai? I see mostly TypeScript and C# stuff?

What "categories" do you think this fits in?

**Comment by Pyromuffin** [comment]
Hi, it’s a tool for parsing jai, syntax highlighting, goto definition, and
intellisense in IDEs that support the language server protocol. i think it
fits under the tool category.

**Comment by smari** [comment]
Ah right! Thanks. Will add.
